name: Run test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [ core, user-data, user-domain, user-ui, app ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests for :${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:testDebugUnitTest

      - name: Run lint for :${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:lintDebug