name: Run test

on:
  pull_request:
    branches: [master]
  branch_protection_rule:
    types: [deleted, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v3

      - name: Detect Changed Modules
        id: detect
        run: |
          git fetch origin master
          CHANGED_MODULES=$(git diff --name-only origin/master...HEAD | cut -d/ -f1 | sort -u | grep -E '^(core|user-data|user-domain|user-ui|app)$' || true)
          echo "Detected modules:"
          echo "$CHANGED_MODULES"
          
          # Prepare CLI-friendly Gradle tasks
          TASKS=""
          for mod in $CHANGED_MODULES; do
            TASKS="$TASKS :$mod:testDebugUnitTest :$mod:lintDebug"
          done
          
          if [ -z "$TASKS" ]; then
            echo "No modules changed. Skipping test."
            echo "run_test=false" >> $GITHUB_OUTPUT
          else
            echo "run_test=true" >> $GITHUB_OUTPUT
            echo "tasks=$TASKS" >> $GITHUB_OUTPUT
          fi      

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests & Lint for Changed Modules
        if: steps.detect.outputs.run_test == 'true'
        run: ./gradlew ${{ steps.detect.outputs.tasks }} --build-cache --no-daemon --continue

      - name: Upload All Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/testDebugUnitTest/
            **/build/reports/lint-results-debug.html

      - name: Upload Jacoco Report (only if app module changed)
        if: steps.detect.outputs.run_jacoco == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: app/build/reports/jacoco/jacocoTestReport/html
